// Client-side SQLite schema — generated by the PowerSync dashboard (Client SDK
// Setup) from the deployed Sync Streams, converted from TS to JS. PowerSync adds
// an implicit `id` TEXT primary key to every table, so `id` is not declared.
// For composite-key tables the streams alias workspace + natural key into `id`;
// the original column still arrives via SELECT * and is declared below. jsonb columns sync as
// JSON text; booleans as 0/1 integers. Keep in step with powersync/sync-rules.yaml.

import { column, Schema, Table } from "@powersync/web";

// trackPrevious on shared documents/composite-key tables: uploads need the
// ancestor for three-way folds; DELETE ops also need previous workspace/key
// values when queued under a different workspace than the active one.
const service_tables = new Table(
  {
    // id column (text) is automatically included
    table_id: column.integer,
    data: column.text,
    updated_at: column.text,
    workspace_id: column.text,
  },
  { indexes: {}, trackPrevious: true },
);

const service_settings = new Table(
  {
    // id column (text) is automatically included
    state: column.text,
    updated_at: column.text,
    workspace_id: column.text,
  },
  { indexes: {}, trackPrevious: true },
);

const reservations = new Table(
  {
    // id column (text) is automatically included
    date: column.text,
    table_id: column.integer,
    data: column.text,
    created_at: column.text,
    workspace_id: column.text,
  },
  // Reservation data is a busy shared document (planner + terrace + service).
  // Its upload fold needs the device's pre-edit ancestor to preserve changes
  // made on another device while this op was offline.
  { indexes: {}, trackPrevious: true },
);

const menu_courses = new Table(
  {
    // id column (text) is automatically included
    position: column.integer,
    menu: column.text,
    veg: column.text,
    hazards: column.text,
    na: column.text,
    wp: column.text,
    os: column.text,
    premium: column.text,
    is_snack: column.integer,
    is_last_bite: column.integer,
    updated_at: column.text,
    gluten_free: column.text,
    dairy_free: column.text,
    nut_free: column.text,
    pescetarian: column.text,
    no_red_meat: column.text,
    no_pork: column.text,
    no_game: column.text,
    no_offal: column.text,
    egg_free: column.text,
    menu_si: column.text,
    course_key: column.text,
    optional_flag: column.text,
    section_gap_before: column.integer,
    show_on_short: column.integer,
    short_order: column.integer,
    force_pairing_title: column.text,
    force_pairing_sub: column.text,
    kitchen_note: column.text,
    vegan: column.text,
    shellfish_free: column.text,
    no_alcohol: column.text,
    no_garlic_onion: column.text,
    halal: column.text,
    low_fodmap: column.text,
    wp_si: column.text,
    na_si: column.text,
    os_si: column.text,
    premium_si: column.text,
    restrictions_si: column.text,
    aperitif_btn: column.text,
    optional_pairing_enabled: column.integer,
    optional_pairing_default_on: column.integer,
    optional_pairing_alco: column.text,
    optional_pairing_alco_si: column.text,
    optional_pairing_na: column.text,
    optional_pairing_na_si: column.text,
    optional_pairing_flag: column.text,
    optional_pairing_label: column.text,
    course_category: column.text,
    force_pairing_title_si: column.text,
    force_pairing_sub_si: column.text,
    is_active: column.integer,
    workspace_id: column.text,
  },
  { indexes: {}, trackPrevious: true },
);

const wines = new Table(
  {
    // id column (text) is automatically included
    key: column.text,
    producer: column.text,
    name: column.text,
    wine_name: column.text,
    vintage: column.text,
    region: column.text,
    country: column.text,
    by_glass: column.integer,
    updated_at: column.text,
    source: column.text,
    workspace_id: column.text,
  },
  { indexes: {}, trackPrevious: true },
);

const beverages = new Table(
  {
    // id column (text) is automatically included
    category: column.text,
    name: column.text,
    notes: column.text,
    position: column.integer,
    updated_at: column.text,
    source: column.text,
    workspace_id: column.text,
  },
  { indexes: {} },
);

const service_archive = new Table(
  {
    // id column (text) is automatically included
    date: column.text,
    label: column.text,
    state: column.text,
    created_at: column.text,
    deleted_at: column.text,
    workspace_id: column.text,
  },
  { indexes: {} },
);

export const AppSchema = new Schema({
  service_tables,
  service_settings,
  reservations,
  menu_courses,
  wines,
  beverages,
  service_archive,
});
